### ISSUE TITLE
default query parameter not being merged within [:domkm.silk/url :query]

### ISSUE THREAD

**Issue by geraldodev** [DomKM/silk#7]
I'was kind of rewriting a buddy example https://github.com/niwibe/buddy/blob/master/examples/sessionexample/src/sessionexample/core.clj which uses another routing library and came to this:

The :next default key is present but not within [:domkm.silk/url :query]
```
(silk/arrive 
  (silk/routes [[:home-page [["login"] {"next" (silk/? :next {:next "/"}) }] ]]) 
  "/login?foo=bar")
dev=> (pp)
{:domkm.silk/url
 {:scheme nil,
  :user nil,
  :host nil,
  :port nil,
  :path ["login"],
  :query {"foo" "bar"},
  :fragment nil},
 :domkm.silk/routes #<Routes domkm.silk.Routes@5c383a2f>,
 :domkm.silk/pattern
 {:query
  {"next"
   #<silk$_QMARK_$reify__10692 domkm.silk$_QMARK_$reify__10692@6f7412f5>},
  :path ["login"]},
 :domkm.silk/name :home-page,
 :next "/"}
```
Two points:
When you have just one query parameter and it's defined as default.
1) The default mechanism does not trigger unless you have a bogus query parameter as above
```
dev=> (silk/arrive 
        (silk/routes [[:home-page 
                       [["login"] {"next" (silk/? :next {:next "/"}) }] ]]) 
        "/login")
nil
```
That forces me to write two rules for this case.

2) Even when it triggers the default value does not appear in :query

**Comment by Deraen** [comment]
Hi,

I also bumped into this. I found two workarounds for my problem but I think this could be quite easily fixed.

```clj
(def routes
  (silk/routes [[:search [["users"] {"q" :q}]]
                [:search [["users"]]]]))

(def routes
  (silk/routes {:search [["users"] (silk/? {"q" (silk/? :q {:q "a"})} {:q "b"})]}))
; If no query params at all -> {:q "b"}, if has query params but no "q" -> {:q "a"}.
```

I took a quick look at the implementation and it looks to me that `url` function used by arrive already creates empty map for query params always, so the problem is probably that `Pattern` implementation of `PersistentArrayMap` is only calling match for keys which are present in the url.

Maybe the match implementation of map could call `match-coll` with something like `(set (concat (keys this) (keys that)))`? Then match would be called for query string keys in the url and in the pattern?
